# Colors (Monokai Pro)
colors:
    # Default colors
    primary:
        background: '#1b1b1b'
        foreground: '#eeffff'

    # Normal colors
    normal:
        black:   '#424242'
        red:     '#e06c75'
        green:   '#98c379'
        yellow:  '#e5c07b'
        blue:    '#56b6c2'
        magenta: '#c678dd'
        cyan:    '#61afef'
        white:   '#eeffff'

    # Bright colors
    bright:
        black:   '#424242'
        red:     '#e06c75'
        green:   '#98c379'
        yellow:  '#e5c07b'
        blue:    '#56b6c2'
        magenta: '#c678dd'
        cyan:    '#61afef'
        white:   '#eeffff'
    cursor:
        text: CellBackground
        cursor: '#e5c07b'


window:
    padding:
        x: 12
        y: 12

scrolling:
    history: 1000

font:
    normal:
        family: FiraCode Nerd Font Mono
        style: Regular
    bold:
        family: FiraCode Nerd Font Mono
        style: Bold
    italic:
        family: FiraCode Nerd Font Mono
        style: Italic
    bold_italic:
        family: FiraCode Nerd Font Mono
        style: SemiBold

    size: 8

cursor:
    style:
        shape: Underline
        blinking: On
    thickness: 0.4
    blink_interval: 600

key_bindings:
    - { key: Minus, mods: Control|Shift, action: IncreaseFontSize }
