# Colors (Monokai Pro)
colors:
    # Default colors
    primary:
        background: '#2D2A2E'
        foreground: '#FCFCFA'

    # Normal colors
    normal:
        black:   '#403E41'
        red:     '#FF6188'
        green:   '#A9DC76'
        yellow:  '#FFD866'
        blue:    '#78DCE8'
        magenta: '#AB9DF2'
        cyan:    '#FC9867'
        white:   '#FCFCFA'

    # Bright colors
    bright:
        black:   '#727072'
        red:     '#FF6188'
        green:   '#A9DC76'
        yellow:  '#FFD866'
        blue:    '#78DCE8'
        magenta: '#AB9DF2'
        cyan:    '#FC9867'
        white:   '#FCFCFA'
    cursor:
        text: CellBackground
        cursor: '#FF6188'


window:
    padding:
        x: 12
        y: 12

scrolling:
    history: 1000

font:
    normal:
        family: CozetteVector
        style: Regular
    bold:
        family: CozetteVector
        style: Regular
    italic:
        family: CozetteVector
        style: Regular
    bold_italic:
        family: CozetteVector
        style: Regular

    size: 9

cursor:
    style:
        shape: Underline
        blinking: On
    thickness: 0.4
    blink_interval: 600

key_bindings:
    - { key: Minus, mods: Control|Shift, action: IncreaseFontSize }
